
eureka:
  client:
    service-url: http://localhost:8761/eureka/

spring:
  application:
    name: config-server

    cloud:
      config:
        server:
          git:
            uri: https://github.com/shoyebmd424/product-store.git
            clone-on-start: true
            default-label: main
            searchPaths: congfigserver/src/main/resources

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      connect-timeout: 1s
      encoding: json
      read-timeout: 10s
  endpoints:
    web:
      exposure:
        include: health,info,metrics,zipkin